Move to npm and remove pug as a dependency
nextcloud/nextcloud-vue-dashboard pull request #163
Opened 2021-03-03 15:06 UTC by juliushaertl

- Move to npm instead of yarn to avoid confusion and two lockfiles
- Manually remove pug from the package-lock dependencies since it only seems to be pulled in as one of the dev/optional dependencies of `@vue/component-compiler` https://github.com/vuejs/vue-component-compiler/blob/64213d92fbc4ce2ef724fd3670d9c2f67a371b83/package.json#L33-L60 and is not used by us in any way

2021-03-03 15:07 UTC, juliushaertl commented
node-forge and axios are already up to date in the package-lock.json though not in the yarn.lock for some reason.

2021-03-03 15:56 UTC, skjnldsv approved these changes

2021-03-03 16:00 UTC, eneiluj requested changes
I first thought `rn` was an alias of `run` but it's definitely a typo :grin:.
All good for the rest.

2021-03-03 16:00 UTC, eneiluj commented on README.md
> +npm rn build
```suggestion
npm run build
```

2021-03-03 16:19 UTC, juliushaertl commented on README.md
> +npm rn build
Woops, good catch :) Fixed

2021-03-03 17:39 UTC, eneiluj approved these changes

2021-03-04 07:07 UTC, merged

2021-03-04 21:27 UTC, nickvergessen commented
Time for 1.1 or 2.0 🚀